# 客户端配置
# 文档地址：https://gofrp.org/zh-cn/docs/reference/client-configures/

# 连接服务端的地址
serverAddr = "xxx.xxx.xxx.xxx"

# 连接服务端的端口
serverPort = 7000

# 你的代理名称将被更改为 {user}.{proxy}
user = "your_name"


# #################################################
# ##################### 日志配置 ###################
# #################################################


# 日志文件输出路径，相对于 frps 可执行文件位置
log.to = "./frps.log"

# 日志记录级别：trace, debug, info, warn, error
log.level = "info"

# 日志文件保留天数，超过天数的日志文件会被自动删除
log.maxDays = 3

# 是否禁用控制台日志的颜色输出，false 表示保留颜色
log.disablePrintColor = false


# #################################################
# #################### 代理配置 ####################
# #################################################


[[proxies]]
# 代理名称
name = "ssh"
# 代理类型
type = "tcp"
# 被代理的本地服务 IP
localIP = "127.0.0.1"
# 被代理的本地服务端口
localPort = 22
# 服务端绑定的端口
remotePort = 6001
